server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: equipment-service
          uri: lb://equipment-service
          predicates:
            - Path=/equipments/**
        - id: rental-service
          uri: lb://rental-service
          predicates:
            - Path=/rentals/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
