spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/db_rental_system_equipments
    password: sasa
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: ${PORT:0}
logging:
  level:
    org:
      hibernate:
        SQL: debug
jwt:
  secret: TaQ+HaV^uvCHrFsEVfypW#7g9%k*Z8$V
